app_backend_profile:
    pattern:  /profile
    defaults: { _controller: AppBackendBundle:Profile:edit }

app_backend_error_403:
    pattern:  /error403
    defaults: { _controller: AppBackendBundle:Default:error403 }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
