app_backend_profile:
    pattern:  /profile
    defaults: { _controller: AppBackendBundle:Profile:edit }

app_backend_error_403:
    pattern:  /error403
    defaults: { _controller: AppBackendBundle:Default:error403 }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile