imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.memcached
    serializer:
        cache: serializer.mapping.cache.doctrine.memcached

doctrine:
    orm:
        metadata_cache_driver: apc
        query_cache_driver:
            type: memcached
            host: %memcached_host%
            port: %memcached_port%
            class: Doctrine\Common\Cache\MemcachedCache
            instance_class: Memcached
        result_cache_driver:
            type: memcached
            host: %memcached_host%
            port: %memcached_port%
            class: Doctrine\Common\Cache\MemcachedCache
            instance_class: Memcached

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console

twig:
    globals:
        assetsPath: assets-built
